env:
    SPELLCK_LINT_DICT=/usr/share/dict/words
notifications:
    email: false
install:
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
script:
  - cargo build --verbose && cargo test --verbose
  #- cargo doc --verbose && mv target/doc doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
